# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8df1c0480d46aec1d68638f072202dc48f3ad402730adf480fd51b5eb75d7e3d9b188a308f741ac1baa2d999863c7d452bef5326baf1900af9c4db375c49b13a

test:
  secret_key_base: c902a75e7a5848f9a38c82430ee9c41b21b260d5c57b92e2f29a62caced9ccf0108557adfbbff67d0411f79449b7cad6e26ffc2308a46ad4c972b9e7861cde26

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
